### ISSUE TITLE
道路交通情報をコード内入れると、バ部と交通情報以外のタイムラインのトゥートを拾うとエラー

### ISSUE THREAD

**Issue by mochimilk** [mochimilk/retia-project#14]
お手上げ
ローカルタイムラインとホームタイムライン両方で確認。
本番環境のサーバでも同じエラー

----------------------------
UPDATE_LOCAL,2018-03-21 18:04:56//もっちー/れてぃあたん
BBCK: No Babu
KawaiiCK: No Sweetie
HCK: No Ecchi
Next: None
PASTCK: False
TOOT: Toot OK.  /
Exception in thread Thread-1:
Traceback (most recent call last):
  File "c:\program files (x86)\python36-32\Lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "c:\program files (x86)\python36-32\Lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "stream.py", line 457, in t_local
    mastodon.stream_local(listener)
  File "<decorator-gen-67>", line 2, in stream_local
  File "D:\web\Python\mstdn-bot\env\lib\site-packages\mastodon\Mastodon.py", line 57, in wrapper
    return function(self, *args, **kwargs)
  File "D:\web\Python\mstdn-bot\env\lib\site-packages\mastodon\Mastodon.py", line 1403, in stream_local
    return self.__stream('/api/v1/streaming/public/local', listener, async=async)
  File "D:\web\Python\mstdn-bot\env\lib\site-packages\mastodon\Mastodon.py", line 1730, in __stream
    listener.handle_stream(r)
  File "stream.py", line 238, in handle_stream
    super().handle_stream(response)
  File "D:\web\Python\mstdn-bot\env\lib\site-packages\mastodon\streaming.py", line 57, in handle_stream
    self._dispatch(event)
  File "D:\web\Python\mstdn-bot\env\lib\site-packages\mastodon\streaming.py", line 106, in _dispatch
    handler(payload)
  File "stream.py", line 326, in on_update
    spoiler_text = spo_text
  File "<decorator-gen-35>", line 2, in status_post
  File "D:\web\Python\mstdn-bot\env\lib\site-packages\mastodon\Mastodon.py", line 57, in wrapper
    return function(self, *args, **kwargs)
  File "D:\web\Python\mstdn-bot\env\lib\site-packages\mastodon\Mastodon.py", line 951, in status_post
    return self.__api_request('POST', '/api/v1/statuses', params)
  File "D:\web\Python\mstdn-bot\env\lib\site-packages\mastodon\Mastodon.py", line 1613, in __api_request
    error_msg)
mastodon.Mastodon.MastodonAPIError: ('Mastodon API returned error', 500, 'Internal Server Error', None)

**Comment by mochimilk** [comment]
issue #13と同じ方法で条件にマッチしなければトゥート生成させないようにすることで暫定対応
